# Define a 'Service' To Expose mysql to Other Services
apiVersion: v1
kind: Service
metadata:
  name: mysql  # DNS name
  labels:
    app: mysql
    tier: database
spec:
  ports:
    # - protocol: TCP
    - port:  {{ .Values.app.container.port }}
      targetPort:  {{ .Values.app.container.port }}
  selector:       # mysql Pod Should contain same labels
    app: mysql
    tier: database
  # clusterIP: None  # We Use DNS, Thus ClusterIP is not relevant
  type: ClusterIP # type of the service.
